### ISSUE TITLE
--no-u2f flag broken

### ISSUE THREAD

**Issue by kaczmarczyck** [google/OpenSK#316]
The flag to deploy without U2F is broken.

## Expected Behavior
OpenSK is deployed.

## Actual Behavior
```sh
Traceback (most recent call last):
  File "/usr/local/google/home/kaczmarczyck/fido2/OpenSK/./deploy.py", line 918, in <module>
    partial_args, _ = main_parser.parse_known_args()
  File "/usr/lib/python3.9/argparse.py", line 1863, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/usr/lib/python3.9/argparse.py", line 2072, in _parse_known_args
    start_index = consume_optional(start_index)
  File "/usr/lib/python3.9/argparse.py", line 2012, in consume_optional
    take_action(action, args, option_string)
  File "/usr/lib/python3.9/argparse.py", line 1940, in take_action
    action(self, namespace, argument_values, option_string)
  File "/usr/local/google/home/kaczmarczyck/fido2/OpenSK/./deploy.py", line 250, in __call__
    if self.const in items:
TypeError: argument of type 'NoneType' is not iterable
```

## Steps to Reproduce the Problem

Setup as usual, then deploy with:
```sh
./deploy.py --board=nrf52840dk --no-u2f
```

## Specifications

- Version: develop
- Platform: Linux

**Comment by jmichelp** [comment]
@kaczmarczyck can you confirm this has been fixed?

**Comment by kaczmarczyck** [comment]
Confirmed, works.
