### ISSUE TITLE
Generating Tock TAB file for application/example ctap2 issue

### ISSUE THREAD

**Issue by dgnkrhn** [google/OpenSK#547]
Hi, I am facing a problem in Generating Tock TAB file stage before flash.

## Actual Behavior
terminal output like this:

info: Generating Tock TAB file for application/example ctap2
Traceback (most recent call last):
  File "/home/dgn/OpenSK/./deploy.py", line 990, in <module>
    main(main_parser.parse_args())
  File "/home/dgn/OpenSK/./deploy.py", line 749, in main
    OpenSKInstaller(args).run()
  File "/home/dgn/OpenSK/./deploy.py", line 634, in run
    self.build_opensk()
  File "/home/dgn/OpenSK/./deploy.py", line 359, in build_opensk
    self._build_app_or_example(is_example=False)
  File "/home/dgn/OpenSK/./deploy.py", line 395, in _build_app_or_example
    self.create_tab_file({props.arch: app_path})
  File "/home/dgn/OpenSK/./deploy.py", line 411, in create_tab_file
    elf2tab_ver = self.checked_command_output(
  File "/home/dgn/OpenSK/./deploy.py", line 290, in checked_command_output
    cmd_output = subprocess.run(
  File "/usr/lib/python3.10/subprocess.py", line 501, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.10/subprocess.py", line 966, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1842, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'elf2tab/bin/elf2tab'

**Comment by kaczmarczyck** [comment]
Hi! Have you run `./setup.sh` before deploying? It contains these lines to install `elf2tab`.

```
mkdir -p elf2tab
rustup install stable
cargo +stable install elf2tab --version 0.6.0 --root elf2tab/
```

**Comment by dgnkrhn** [comment]
By doing  ./reset.sh and /.setup.sh my problem was solved.
Thank you
