### ISSUE TITLE
configure.py error

### ISSUE THREAD

**Issue by Samthebest999** [google/OpenSK#557]
## Expected Behavior
./tools/configure.py     --certificate=crypto_data/opensk_cert.pem     --private-key=crypto_data/opensk.key
info: Private key is valid.
info: Certificate is valid.
info: Programming OpenSK device AAGUID e4020c81-3218-4d8e-8a54-a6dd965ab66f (CtapHidDevice('/dev/hidraw8')).
info: Please touch the device to confirm...                                     
info: Certificate: Present                                                      
info: Private Key: Present                                                      
100%|█████████████████████████████████████████████| 1/1 [00:05<00:00,  5.30s/it]

## Actual Behavior
/tools/configure.py \
    --certificate=crypto_data/opensk_cert.pem \
    --private-key=crypto_data/opensk.key
info: Private key is valid.
info: Certificate is valid.
Traceback (most recent call last):
  File "/home/samit/GitClones/OpenSK/./tools/configure.py", line 196, in <module>
    main(parser.parse_args())
  File "/home/samit/GitClones/OpenSK/./tools/configure.py", line 127, in main
    for authenticator in tqdm(get_opensk_devices(args.batch)):
  File "/home/samit/GitClones/OpenSK/./tools/configure.py", line 65, in get_opensk_devices
    return [ctap2.CTAP2(dev)]
AttributeError: module 'fido2.ctap2' has no attribute 'CTAP2'. Did you mean: 'Ctap2'?

## Steps to Reproduce the Problem

1../tools/configure.py \
    --certificate=crypto_data/opensk_cert.pem \
    --private-key=crypto_data/opensk.key

## Specifications
Feitian Dongle V2
- Version: stable
- Platform:     Ubuntu 22.04.1 LTS Kernel: Linux 5.15.0-48-generic x86_64

**Comment by Samthebest999** [comment]
Fix is in pr #556
